# Generated by Django 5.0.7 on 2024-08-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_words', models.TextField()),
                ('title', models.TextField()),
                ('summary', models.TextField()),
                ('published_date', models.TextField()),
                ('authors', models.TextField()),
                ('paper_url', models.TextField()),
                ('pdf_path', models.TextField()),
                ('create_time', models.TextField()),
            ],
        ),
    ]
