# Generated by Django 5.0.7 on 2024-08-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='paper_url',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='published_date',
            field=models.TextField(),
        ),
    ]
